use Users_db

db.users.insertMany([{name: "Alice", age:null, nationality: "Egypt", email: "alice@gmail.com"},
	{name: "John", age:50, nationality: "Morocco", email: "john@gmail.com"},
	{name: "Mark", age:23, nationality: "UK", email: "mark@gmail.com"},
	{name: "Victor", age:87, nationality: "Zanzibar", email: "victor@gmail.com"},
	 { name: "Alice", age: 28, nationality: "Egypt", email: "alice@gmail.com" },
	  { name: "John", age: 50, nationality: "Morocco", email: "john@gmail.com" },
	  { name: "Mark", age: 23, nationality: "UK", email: "mark@gmail.com" },
	  { name: "Victor", age: 87, nationality: "Zanzibar", email: "victor@gmail.com" },
	  { name: "Clement", age: 26, nationality: "Kenya", email: "clement@gmail.com" },
	  { name: "Maria", age: 32, nationality: "Spain", email: "maria.spain@gmail.com" },
	  { name: "Ahmed", age: 41, nationality: "Egypt", email: "ahmed_egypt@yahoo.com" },
	  { name: "Naomi", age: 19, nationality: "Japan", email: "naomi.jp@gmail.com" },
	  { name: "Carlos", age: 36, nationality: "Mexico", email: "carlosmx@gmail.com" },
	  { name: "Fatima", age: 45, nationality: "Morocco", email: "fatima.morocco@gmail.com" },
	  { name: "Yusuf", age: 29, nationality: "Nigeria", email: "yusuf.ng@gmail.com" },
	  { name: "Elena", age: 52, nationality: "Greece", email: "elena.greece@gmail.com" },
	  { name: "Liu", age: 34, nationality: "China", email: "liu.china@gmail.com" },
	  { name: "Aisha", age: null, nationality: "Kenya", email: "aisha@gmail.com" },
	  { name: "George", age: 60, nationality: "USA", email: "george.usa@gmail.com" },
	  { name: "Rita", age: 25, nationality: "Brazil", email: "rita.br@gmail.com" },
	  { name: "Hassan", age: 38, nationality: "Tunisia", email: "hassan.tn@gmail.com" },
	  { name: "Anna", age: 30, nationality: "Poland", email: "anna.pl@gmail.com" },
	  { name: "Nour", age: 21, nationality: "Lebanon", email: "nour.lb@gmail.com" },
	  { name: "Kofi", age: 47, nationality: "Ghana", email: "kofi.gh@gmail.com" }])
